export const FETCH_PLATFORM_SUCCESS = 'FETCH_PLATFORM_SUCCESS';
export const FETCH_PLATFORM_STARTED = 'FETCH_PLATFORM_STARTED';
export const FETCH_PLATFORM_ERROR = 'FETCH_PLATFORM_ERROR';
export const FILTER_PLATFORMS = 'FILTER_PLATFORMS';