export const FETCH_PLATFORM_ARTICLES = 'FETCH_PLATFORM_ARTICLES';
export const FETCH_PLATFORM_ARTICLES_STARTED = 'FETCH_PLATFORM_ARTICLES_STARTED';
export const FETCH_PLATFORM_ARTICLES_SUCCESS = 'FETCH_PLATFORM_ARTICLES_SUCCESS';
export const FETCH_PLATFORM_ARTICLES_ERROR = 'FETCH_PLATFORM_ARTICLES_ERROR';