export const FETCH_PLATFORM_NEWS = 'FETCH_PLATFORM_NEWS';
export const FETCH_PLATFORM_NEWS_STARTED = 'FETCH_PLATFORM_NEWS_STARTED';
export const FETCH_PLATFORM_NEWS_SUCCESS = 'FETCH_PLATFORM_NEWS_SUCCESS';
export const FETCH_PLATFORM_NEWS_ERROR = 'FETCH_PLATFORM_NEWS_ERROR';